import { type } from "os";

export const REQUEST_FILMS = 'FILMS/REQUEST_FILMS';
export const FETCH_FILMS = 'FILMS/FETCH_FILMS';

export const SORTING_FILMS_YEAR = 'SORTING/YEAR';
export const SORTING_FILMS_TITLE_STRAIGHT = 'SORTING/STRAIGHT';
export const SORTING_FILMS_TITLE_REVERSE = 'SORTING/REVERSE';

export const REQUEST_FULL_INFO = 'FILM/REQUEST_MOVIE';
export const FETCH_FILM_FULL = 'FILM/FETCH_FILM_FULL';

export const GET_MOVIES_WTH_FAILURE = 'GET_MOVIES_WTH_FAILURE';
export const GET_MOVIE_WTH_FAILURE = 'GET_MOVIE_WTH_FAILURE';

